name: Release

on:
  release:    
    types: [published,edited]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      
    - name: Fetch all tags and branches
      run: git fetch --prune --unshallow
        
    - name: Install .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        # gitversion needs 5.0 and we need all SDKs the project is targeting
        dotnet-version: | 
          3.1.x
          5.0.x
          6.0.x
        
    - name: run cake
      uses: ecampidoglio/cake-action@v1
      with:
        target: Publish        
      env: 
        nugetApiKey: ${{ secrets.nugetApiKey }}  
