name: Release

on:
  release:    
    types: [published,edited]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: | 
          3.1.x
          5.0.x
          6.0.x
        
    - name: run cake
      uses: ecampidoglio/cake-action@v1
      with:
        target: Publish        
      env: 
        nugetApiKey: ${{ secrets.nugetApiKey }}  
